### ISSUE TITLE
DOTStateProvider生成地址不一致

### ISSUE THREAD

**Issue by liweiww123** [pengpengliu/bitcorej#2]
私钥：0xd3d8015b804bcf9114a62038e203fc87c8d7658568dc2116b936a81a0eef99fd

生成钱包地址应该是：14SWSpQQjSafs3zniZrDrbPx89iu1BbAi3vNA3gSuuiiC1FU

用DOTStateProvider生成的是143xvTPy2mBHT4D3RMZYfgXPctxarifRKQmyGaqAf9cs9XTH

请检查下，谢谢

**Comment by pengpengliu** [comment]
@liweiww123 密钥对类型是Ed25519
