### ISSUE TITLE
DOTStateProvider生成 地址不一样

### ISSUE THREAD

**Issue by liweiww123** [pengpengliu/bitcorej#3]
私钥：0xd3d8015b804bcf9114a62038e203fc87c8d7658568dc2116b936a81a0eef99fd

生成钱包地址应该是：14SWSpQQjSafs3zniZrDrbPx89iu1BbAi3vNA3gSuuiiC1FU

用DOTStateProvider生成的是143xvTPy2mBHT4D3RMZYfgXPctxarifRKQmyGaqAf9cs9XTH

请检查下，谢谢

**Comment by pengpengliu** [comment]
@liweiww123 密钥对类型是Ed25519

**Comment by liweiww123** [comment]
@pengpengliu 
你好，执行的是
KeyPair keyPair =generateKeyPair("0xd3d8015b804bcf9114a62038e203fc87c8d7658568dc2116b936a81a0eef99fd");
keyPair.getPublic()="143xvTPy2mBHT4D3RMZYfgXPctxarifRKQmyGaqAf9cs9XTH";


addressType=new byte[]{0x00};

 public static KeyPair generateKeyPair(String secret) {
        Ed25519 keyPair = new Ed25519(NumericUtil.hexToBytes(secret));
        byte[] bytes = ByteUtil.concat(addressType, keyPair.pubkey());

        byte[] hash = HashUtil.hashB(ByteUtil.concat(SS58_PREFIX, bytes), 512);
        byte[] checksum = copyOfRange(hash, 0, 2);
        return new KeyPair(secret, Base58.encode(ByteUtil.concat(bytes, checksum)));
    }

**Comment by pengpengliu** [comment]
143xvTPy2mBHT4D3RMZYfgXPctxarifRKQmyGaqAf9cs9XTH 是正确的地址

你可以使用这个网页钱包尝试(需要在高级选项里面将密钥对类型改为ed25519
https://polkadot.js.org/apps/#/accounts

**Comment by pengpengliu** [comment]
我导入0xd3d8015b804bcf9114a62038e203fc87c8d7658568dc2116b936a81a0eef99fd的尝试：
ed25519的地址: 143xvTPy2mBHT4D3RMZYfgXPctxarifRKQmyGaqAf9cs9XTH
sr25519的地址: 14SWSpQQjSafs3zniZrDrbPx89iu1BbAi3vNA3gSuuiiC1FU

**Comment by liweiww123** [comment]
@pengpengliu 
明白了，感谢！

**Comment by liweiww123** [comment]
@pengpengliu  
试了下，的确是这个问题，想问您，您写这个思路在哪里看到的 呢，我现在想集成polkadot的钱包 ， 但是网上的资源蛮少的，特别是java的，想问下您是在哪里找到资料的呢，比如这个Ed25519

**Comment by pengpengliu** [comment]
去读官方的源码和其他语言的实现
